### ISSUE TITLE
When editing recipe..

### ISSUE THREAD

**Issue by chueny** [PeterBaker644/Recipe-Journal#71]
EDIT ingredients page: 
-the new ingredient does not show up.  It saves "unit" in the ingredient column and the X (delete) in the measurement column.

-Same thing happening in the EDIT STEPS. (Step # not showing up.  The details show up in this column instead).  See screenshots below.
 
![Screen Shot 2020-09-15 at 2 48 07 PM](https://user-images.githubusercontent.com/17972802/93257473-83e68600-f762-11ea-8be7-a4e45d2284c6.png)

![Screen Shot 2020-09-15 at 2 47 56 PM](https://user-images.githubusercontent.com/17972802/93257513-9234a200-f762-11ea-9536-6875262be88c.png)

**Comment by PeterBaker644** [comment]
Fixed a while ago.
